version: '3.3'

services:
  nginx:
    container_name: nginx_ct
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"

  a1:
    container_name: a1_ct
    image: ss-web-app

  a2:
    container_name: a2_ct
    image: ss-web-app

  a3:
    container_name: a3_ct
    image: ss-web-app

